version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2000000000
      KAFKA_HEAP_OPTS: "-Xms4G -Xmx4G"
      KAFKA_ATHURIZER_CLASS_NAME: all
      KAFKA_LOG4J_LOGGERS: "kafka.controller=DEBUG,kafka.producer.async.DefaultEventHandler=DEBUG,state.change.logger=DEBUG"
    networks:
      - kafka

  neo4j:
    image: neo4j:5.20.0
    container_name: neo4j
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/conf:/conf
    ports:
      - 7474:7474
      - 7687:7687
      - 21118:7474
    environment:
      - NEO4J_AUTH=neo4j/changeme # change password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    restart: on-failure
    command: neo4j
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
